### ISSUE TITLE
save sampled values as a new shapefile point layer

### ISSUE THREAD

**Issue by landam** [ctu-geoforall-lab-projects/bp-kala-2017#5]
https://pcjericks.github.io/py-gdalogr-cookbook/vector_layers.html#create-a-new-shapefile-and-add-data

* overwrite
* crs from input data (or map canvas)

**Comment by landam** [comment]
To be done:

* remove output shapefile from layer tree

**Comment by landam** [comment]
To be done:

* save sample values in attribute table
* csv file with same attributes

**Comment by landam** [comment]
Fix cvs formatting (tab -> comma)

**Comment by kalator** [comment]
Add atribute cumulative dose rate to both csv and shape file
