### ISSUE TITLE
thread aware computation

### ISSUE THREAD

**Issue by landam** [ctu-geoforall-lab-projects/bp-kala-2017#6]
* Move computation to separate thread
* Show progress using pushMessage()

See https://github.com/ctu-geoforall-lab/qgis-ruian-plugin/blob/master/MainApp.py#L495

**Comment by kalator** [comment]
[Hide x button](https://gis.stackexchange.com/questions/238508/what-signal-does-x-button-in-messagebar-emmit-or-how-to-get-rid-of-it-using-pyqg)
